const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  cart: "/cart",
  checkout: "/checkout",
  checkoutSuccess: "/checkout/success",
  account: "/account",
  accountOrder: "/account/order",
  accountLatest: "/account/latest",
  accountFavorite: "/account/favorite",
  dashboard: "/dashboard",
  orderManagement: "/dashboard/order",
  commentManagement: "/dashboard/comment",
  categoryManagement: "/dashboard/category",
  groupCategoryManagement: "/dashboard/group-category",
  groupProductManagement: "/dashboard/group-product",
  discountManagement: "/dashboard/discount",
  productManagement: "/dashboard/product",
  colorManagement: "/dashboard/color",
  sizeManagement: "/dashboard/size",
  userManagement: "/dashboard/user",
  roleManagement: "/dashboard/role",
  couponManagement: "/dashboard/coupon",
  websiteManagement: "/dashboard/website",
  productDetailManagement: "/dashboard/product-detail",
  statistics: "/dashboard/statistics",
  productCategory: "/:category_slug",
  search: "/search",
  changePassword: "/account/change-password",
  productAdd: "/dashboard/product/add",
  productEdit: "/dashboard/product/edit/:id",
};

export default routes;
